\newfontfamily\headerfont[
  Path=\@fontdir,
  UprightFont=*-Regular,
  ItalicFont=*-Italic,
  BoldFont=*-Medium
]{DMMono}

\newfontfamily\headerfontlight[
  Path=\@fontdir,
  UprightFont=*-Light,
  ItalicFont=*-Italic,
]{DMMono}

\newfontfamily\bodyfontlight[
Path=\@fontdir,
UprightFont=*-Regular,
ItalicFont=*-Italic,
BoldFont=*-Medium]{DMMono}

\newfontfamily\bodyfont[
Path=\@fontdir,
UprightFont=*-Regular]{DMMono}

\newfontfamily\footerfont[
Path=\@fontdir,
UprightFont=*-Regular,
ItalicFont=*-Italic,
BoldFont=*-Medium]{DMMono}

